version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: pg-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
      - exportdata:/var/lib/postgresql/export

volumes:
  pgdata:
  exportdata: